name: 'Artifactory Publishing Action'
description: 'Publishes Artifacts to Artifactory'
inputs:
  endpoint:
    description: 'Artifactory URL (full path to helm repo)'
    required: true
  username:
    description: 'Username'
    required: true
  password:
    description: 'Password'
    required: true
  version:
    default: 'version'
    required: true
  repoName:
    description: 'Repo Name'
    required: true
  chart:
    description: "Chart"
    required: true
runs:
  using: "composite"
  steps:
    - run: echo "Listing Current Dir" && ls -lah
      shell: bash
    - run: |
        echo "Installing Helm"
        curl https://baltocdn.com/helm/signing.asc | sudo apt-key add -
        sudo apt-get install -y apt-transport-https
        echo "deb https://baltocdn.com/helm/stable/debian/ all main" | sudo tee /etc/apt/sources.list.d/helm-stable-debian.list
        sudo apt-get update
        sudo apt-get install -y helm curl
      shell: bash
    - run: |
        echo "Packaging chart ${{ inputs.chart }}"
        helm package ${{ inputs.chart }}
        echo "Publishing Helm Chart"
        curl -u ${{ inputs.username }}:${{ inputs.password }} -T ${{ inputs.repoName }}-${{ inputs.version }}.tgz {{ inputs.endpoint }}/${{ inputs.repoName }}/${{ inputs.repoName }}-${{ inputs.version }}.tgz
      shell: bash
