name: 'Artifactory Publishing Action'
description: 'Publishes Artifacts to Artifactory'
inputs:
  endpoint:
    description: 'Artifactory URL (full path to helm repo)'
    required: true
  saUsername:
    description: 'Service Account Name'
    required: true
  saPass:
    description: 'Service Account Password'
    required: true
  accessToken:
    description: 'Service Account Token'
    required: true
  repoName:
    description: 'Repo Name'
    required: true
  chart:
    description: 'Chart location without . before e.g. charts/allure-testops'
    required: true
runs:
  using: "composite"
  steps:
    - run: echo "Listing Current Dir" && ls -lah
      shell: bash
    - run: |
        echo "Installing Helm"
        curl https://baltocdn.com/helm/signing.asc | sudo apt-key add -
        sudo apt-get install -y apt-transport-https
        echo "deb https://baltocdn.com/helm/stable/debian/ all main" | sudo tee /etc/apt/sources.list.d/helm-stable-debian.list
        sudo apt-get update
        sudo apt-get install -y helm
        helm plugin install https://github.com/belitre/helm-push-artifactory-plugin --version v1.0.2
      shell: bash
    - run: |
        echo "Adding Repo ${{ inputs.repoName }}"
        helm repo add --username ${{ inputs.saUsername }} --password ${{ inputs.saPass }} ${{ inputs.repoName }} ${{ inputs.endpoint }}
      shell: bash
    - run: |
        echo "Publishing Helm Chart ${{ inputs.chart }}"
        helm push-artifactory ${{ inputs.chart }} ${{ inputs.repoName }} --access-token ${{ inputs.accessToken }} --skip-reindex
      shell: bash
